Test error handling

diff --git a/.github/workflows/cicd-2-publish.yaml b/.github/workflows/cicd-2-publish.yaml
--- a/.github/workflows/cicd-2-publish.yaml
+++ b/.github/workflows/cicd-2-publish.yaml
@@ -54,7 +54,7 @@ jobs:
     # if: github.event.pull_request.merged == true
     timeout-minutes: 3
     env:
-      release_tag: "MY_RELEASE_TAG"
+      release_tag: ""
       version_bump: "PATCH"
       wiki_path: "wiki/Releases"
     steps:
@@ -71,8 +71,13 @@ jobs:
         with:
           repository: ${{ github.repository }}.wiki
           path: ${{ env.wiki_path }}
+      - if: ${{ env:release_tag == '0.2.28' }}
+        run: |
+          echo "Error: The release tag has not been found"
+          exit 1
       - name: Create Release Notes
         run: |
+          if ${{ env.release_tag }}
           echo "Using following tag to create markdown file: ${{ env.release_tag }}"
           echo "${{ github.event.pull_request.body }}" >> "${{ env.wiki_path }}/v${{ env.release_tag }}.md"
       - name: Push to wiki
